#!/usr/bin/env python3
"""FULL VIDEO #1 - SEGMENT 1A ("RAW SITE -> CLEARED SITE").

First of 7 segments in the planned ~68s production video. This script
builds and runs Segment 1A ONLY - later segments (1B, 2, 3, 4, 5, 6) are
each their own separate, independently-approved script, built one at a
time after this one's result is reviewed. Nothing about segment 1B or
beyond is generated by this file.

Segment 1A covers the very start of the video: the first ~1.5-2s hold on
the completely untouched, spectacular clifftop site (no structure, no
materials of any kind), then the builder rapidly clears brush/scrub with a
brush-cutter through several hard time-lapse jumps, ending with a fully
cleared, bare working area - still with zero construction, ready for site
prep (that's segment 1B).

Two calls, same "reference image, then video from it" pattern as
scripts/run_first_fal_test.py:
  1. Exactly ONE Nano Banana Pro Generate still image (NANO_BANANA_PRO_GENERATE
     in app/providers/image/fal.py) - the segment's START-state reference
     frame (completely untouched site), built from the fixed site
     continuity bible (see below) plus this segment's build-state clause
     and camera clause. No source/reference image is used for this call -
     it's a fresh text-to-image generation, same as the cross-angle
     continuity test.
  2. Exactly ONE Wan 3.0 standard video generation (image-to-video) from
     that still, 480p, 9:16, 6 seconds. WAN_3_0_STANDARD's module-level
     config (app/providers/video/fal.py) is fixed at duration=15 (from the
     earlier 15s timelapse tests) - this script does NOT mutate that
     shared object. Instead it builds a local copy via dataclasses.replace
     with extra_payload={"duration": 6}, the same per-model-config
     extensibility mechanism already used for every other duration
     variant in this project (Kling's "5", Veo's "6s", Seedance's "8").

The site continuity bible (SITE_BIBLE below) is the fixed part of the
production's continuity system - identical text across ALL 7 segments'
reference-image prompts (builder identity, site geometry, ocean
orientation, landmarks, lighting). Only a per-segment BUILD_STATE clause
changes between segments, describing what's changed so far - this is the
same mechanism validated by scripts/run_cross_angle_continuity_test.py,
now extended with a fresh build-state description per segment instead of
just a fresh camera angle. Segment 1A's own two build states (S0 raw ->
S0.5 cleared) are both defined here since this segment produces the video
transition between them; SEGMENT_1A_END_STATE_S0_5 is what segment 1B's
own script (not built yet) will use as its own starting build-state text,
kept here as the single source of truth for that hand-off.

Safety, same pattern as every other real-call script in this repo:
  - Exactly 1 image-generation call, exactly 1 video-generation call. No
    loop, no retry, no auto-regeneration, no other segment.
  - Total cost checked against MAX_SPEND_USD BEFORE either call; one
    "type yes" confirmation gates the whole run.
  - manifest.json records both prompts, both costs, the output paths, and
    the exact build-state text handed off to segment 1B.
  - Job state (provider job id + fal.ai's own status/response URLs) is
    saved to disk immediately after video submission, before polling
    starts, so scripts/recover_fal_video_job.py can recover it if this
    script crashes or is interrupted mid-poll.
  - A mandatory manual REVIEW GATE sits between the two calls: after the
    image is generated, the script prints its path and stops, requiring a
    separate "type yes" before submitting the video job. This second gate
    is NOT skippable by --yes (--yes only skips the upfront spend
    confirmation) - its entire purpose is to let a human judge the actual
    generated image (does it show a completely untouched site, no
    structure, correct framing?) before the larger video spend happens
    from it, rather than trusting the video call to run automatically no
    matter what the image looks like.

Usage (from the repo root, with FAL_API_KEY set in your .env):
    python -m scripts.run_full_video_segment_1a_test
    python -m scripts.run_full_video_segment_1a_test --yes   (skips only the upfront cost confirmation - the image review gate always runs)
"""
import dataclasses
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from app.config import settings
from app.providers.base import (
    ImageGenerationRequest,
    ImageProviderError,
    ProviderJobState,
    VideoGenerationRequest,
    VideoProviderError,
)
from app.providers.image.fal import NANO_BANANA_PRO_GENERATE, FalImageProvider
from app.providers.video.fal import WAN_3_0_STANDARD, FalVideoProvider

MAX_SPEND_USD = 0.45  # $0.15 image + $0.30 video (6s @ $0.05/s) - zero margin
RESOLUTION = "480p"
ASPECT_RATIO = "9:16"
DURATION_SECONDS = 6.0
POLL_INTERVAL_SECONDS = 3
MAX_WAIT_SECONDS = 300  # 5 minutes; see the timeout message below if this is hit

SEGMENT_ID = "1A"

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "data" / "fal_full_video_segment_1a"
MANIFEST_PATH = OUTPUT_DIR / "manifest.json"
JOB_STATE_PATH = OUTPUT_DIR / "last_job.json"

# --- Fixed site continuity bible: IDENTICAL across all 7 segments' -----
# reference-image prompts. Only the BUILD_STATE clause (below) and the
# camera clause change between segments - this is the same "shared bible +
# swapped state/angle" mechanism validated in run_cross_angle_continuity_test.py.
SITE_BIBLE = (
    "A rugged male builder in his mid-40s, with slightly messy dark brown hair, a short dark "
    "beard/stubble, and a medium athletic build, wearing worn faded blue-grey jeans, a plain "
    "heather-grey crew-neck work shirt with no visible logo or branding, and brown leather work "
    "boots, working on a flat rocky clifftop clearing. The clearing is roughly triangular, "
    "narrowing toward a cliff edge that drops sharply 8-10 meters to the ocean; the ocean and "
    "horizon are visible beyond the site. A distinctive large flat grey boulder sits near the "
    "rear/landward corner of the clearing. Sparse wind-bent low shrubs and scrub grass line the "
    "cliff edge, with a narrow dirt access path from the landward side. Warm, low-angle, "
    "late-afternoon golden-hour sunlight from the landward side, long soft shadows. Candid "
    "documentary/observational photography style, vertical 9:16."
)

# Segment 1A's own two build states. S0 is this segment's start (the
# reference image below); S0_5 is this segment's end (the video's final
# state) - not generated as an image here, but recorded in the manifest as
# the exact text segment 1B's own script must reuse as ITS start state, so
# the hand-off between segments stays byte-identical rather than
# re-described from memory.
SEGMENT_1A_START_STATE_S0 = (
    "Current construction state: the clifftop clearing is completely untouched - natural rocky "
    "ground with low brush, small shrubs, loose rock, and some scattered debris across the site. "
    "There is no cabin structure of any kind, no framing, no stakes, no materials, and no tools "
    "laid out beyond what the builder is personally carrying."
)
SEGMENT_1A_END_STATE_S0_5 = (
    "Current construction state: the clearing has been fully cut back and is now visibly bare - "
    "brush, scrub, and debris removed, exposed ground across the whole working area. It is still "
    "completely unbuilt: no stakes, no footprint markings, no materials staged, and no structure "
    "of any kind yet."
)

CAMERA_WIDE_ENVIRONMENTAL = (
    "Camera view: a wide environmental angle, pulled back and slightly elevated, taking in the "
    "whole clifftop clearing - the ocean and cliff edge beyond, the distinctive flat grey boulder "
    "near the rear corner, and the sparse shrubs along the edge - with the builder positioned "
    "within this wide view rather than filling the frame."
)

IMAGE_PROMPT = (
    f"{SITE_BIBLE} {SEGMENT_1A_START_STATE_S0} {CAMERA_WIDE_ENVIRONMENTAL} The builder stands at "
    "the edge of the site holding a brush-cutter, about to begin clearing. He is not looking "
    "toward the camera - his attention is on the site ahead of him. No posing, no presenter stance."
)

VIDEO_PROMPT = (
    "Vertical 9:16, extreme time-lapse construction footage, documentary/observational style. "
    f"{CAMERA_WIDE_ENVIRONMENTAL} He never looks toward the camera.\n\n"
    "The first 1.5-2 seconds hold on the completely untouched clifftop: natural rocky ground, low "
    "brush, small shrubs, scattered loose rock and debris, no structure or materials of any kind - "
    "just the raw, spectacular site. Then: NOT continuous real-time footage - the clearing "
    "advances in hard, visible jumps, with an obvious change approximately every 1.5-2 seconds. "
    "HARD TIME JUMP: the builder is now actively cutting through brush and scrub with a "
    "brush-cutter, moving briskly and purposefully across the site - noticeably faster than "
    "typical real-time work (roughly 25-30% faster), but still physically believable, not "
    "frantic or cartoonish. HARD TIME JUMP: significantly more of the ground is now cut back and "
    "bare, cleared debris piling at the margins. HARD TIME JUMP: the clearing is now fully cut "
    "back - exposed bare ground across the whole working area, no structure, no stakes, no "
    "materials yet, ready for the next stage of work.\n\n"
    "Once ground is cleared it stays cleared - progress only ever moves forward. The ocean is "
    "visible beyond the site with visible wave motion; wind moves the remaining shrubs and scrub "
    "grass; clouds drift overhead. Natural ambient sounds only - brush-cutter engine, cutting, "
    "wind, ocean - no dialogue, no narration, no music. No posing, no presenter behavior, no eye "
    "contact with the camera, no commercial aesthetic."
)

# Local per-segment duration variant - does NOT mutate the shared
# module-level WAN_3_0_STANDARD (still used at duration=15 by the earlier
# 15s timelapse tests). Bare int 6, matching DURATION_SECONDS=6.0 below,
# same "must agree for cost math" requirement as every other fixed-duration
# config in app/providers/video/fal.py.
WAN_3_0_SEGMENT_1A = dataclasses.replace(WAN_3_0_STANDARD, extra_payload={"duration": 6})


def fail(message: str) -> None:
    print(f"\nSTOPPED: {message}")
    print(f"No retry, no further generation - the script is exiting now. Manifest: {MANIFEST_PATH}")
    sys.exit(1)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def save_manifest(manifest: dict) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2))


def main() -> None:
    skip_confirm = "--yes" in sys.argv[1:]

    key_preview = f"{settings.fal_api_key[:6]}..." if settings.fal_api_key else None
    print(f"FAL_API_KEY loaded from .env: {'yes (' + key_preview + ')' if key_preview else 'NO'}")
    if not settings.fal_api_key:
        fail("FAL_API_KEY is not set. Add FAL_API_KEY=your_key_here to your .env file and try again.")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    image_path = OUTPUT_DIR / "segment_1a_start_frame.jpg"
    video_path = OUTPUT_DIR / "segment_1a.mp4"

    image_provider = FalImageProvider(NANO_BANANA_PRO_GENERATE)
    video_provider = FalVideoProvider(WAN_3_0_SEGMENT_1A)

    image_request = ImageGenerationRequest(
        prompt=IMAGE_PROMPT, extra_params={"aspect_ratio": ASPECT_RATIO, "resolution": "1K"}
    )
    image_cost = image_provider.estimate_cost(image_request)

    cost_preview_request = VideoGenerationRequest(
        prompt=VIDEO_PROMPT,
        aspect_ratio=ASPECT_RATIO,
        duration_seconds=DURATION_SECONDS,
        extra_params={"resolution": RESOLUTION},
    )
    video_cost = video_provider.estimate_cost(cost_preview_request)
    total_cost = round(image_cost + video_cost, 4)

    print("=" * 70)
    print(f"FULL VIDEO #1 - SEGMENT {SEGMENT_ID} - THIS WILL SPEND REAL MONEY")
    print("=" * 70)
    print(f"Image model: {NANO_BANANA_PRO_GENERATE.model_id}  (text-to-image, no source image)")
    print(f"Video model: {WAN_3_0_SEGMENT_1A.submit_path}  ({RESOLUTION}, {ASPECT_RATIO}, {DURATION_SECONDS:.0f}s)")
    print(f"\nImage prompt:\n  {IMAGE_PROMPT}")
    print(f"\nVideo prompt:\n  {VIDEO_PROMPT}")
    print(f"\nEstimated cost: ${image_cost:.4f} (image) + ${video_cost:.4f} (video) = ${total_cost:.4f}")
    print(f"Hard cap:       ${MAX_SPEND_USD:.2f}")
    print("Rules: exactly 1 image call, exactly 1 video call, no retries, no other segment.")
    print("=" * 70)

    if total_cost > MAX_SPEND_USD:
        fail(f"Estimated cost ${total_cost:.4f} exceeds the ${MAX_SPEND_USD:.2f} cap. Nothing was generated.")

    if not skip_confirm:
        answer = input(f"\nType 'yes' to spend up to ${total_cost:.4f} and proceed: ").strip().lower()
        if answer != "yes":
            print("Cancelled. Nothing was generated.")
            sys.exit(0)

    manifest = {
        "created_at": _now(),
        "experiment": "full_video_segment_1a",
        "segment_id": SEGMENT_ID,
        "build_state_start": SEGMENT_1A_START_STATE_S0,
        "build_state_end": SEGMENT_1A_END_STATE_S0_5,
        "image_model": NANO_BANANA_PRO_GENERATE.model_id,
        "video_model": WAN_3_0_SEGMENT_1A.submit_path,
        "resolution": RESOLUTION,
        "aspect_ratio": ASPECT_RATIO,
        "duration_seconds": DURATION_SECONDS,
        "image_prompt": IMAGE_PROMPT,
        "video_prompt": VIDEO_PROMPT,
        "max_spend_usd": MAX_SPEND_USD,
        "estimated_cost_usd": total_cost,
        "image_path": None,
        "image_cost_usd": None,
        "video_path": None,
        "video_cost_usd": None,
        "actual_cost_usd": None,
        "completed_at": None,
    }
    save_manifest(manifest)

    # --- Step 1: exactly one reference image (segment start state) ---------
    print(f"\n[1/2] Generating segment {SEGMENT_ID} start-frame reference image (Nano Banana Pro)...")
    t0 = time.monotonic()
    try:
        image_result = image_provider.generate_image(image_request, str(image_path))
    except ImageProviderError as e:
        fail(f"Image generation failed: {e}")
    image_seconds = time.monotonic() - t0
    print(f"      Done in {image_seconds:.1f}s -> {image_path} (${image_result.cost_usd:.4f})")

    manifest["image_path"] = str(image_path)
    manifest["image_cost_usd"] = image_result.cost_usd
    save_manifest(manifest)

    # Mandatory manual review gate - NOT skippable by --yes, unlike the
    # spend confirmation above. The whole point of this pause is to let a
    # human open and judge segment_1a_start_frame.jpg (does it show a
    # completely untouched site, no structure, correct framing?) BEFORE the
    # $0.30 video call is made from it - --yes only ever meant "skip typing
    # yes to the cost I already reviewed in the preflight," not "skip
    # judging output that doesn't exist until this exact moment."
    print(f"\n{'=' * 70}")
    print("REVIEW GATE - open the image below before continuing.")
    print(f"{'=' * 70}")
    print(f"Start-frame image: {image_path}")
    print("Check: completely untouched site, no cabin/materials of any kind,")
    print("wide environmental framing, builder not looking at camera.")
    review_answer = input(
        "\nType 'yes' once you've reviewed the image and want to proceed to the "
        f"${video_cost:.4f} video call (anything else stops here, no video generated): "
    ).strip().lower()
    if review_answer != "yes":
        print("Stopped after image review. No video was generated. Nothing further will happen automatically.")
        sys.exit(0)

    # --- Step 2: exactly one video, from that exact image -------------------
    print(f"\n[2/2] Submitting segment {SEGMENT_ID} video generation job (Wan 3.0 standard, {RESOLUTION})...")
    video_request = VideoGenerationRequest(
        prompt=VIDEO_PROMPT,
        reference_image_path=str(image_path),
        aspect_ratio=ASPECT_RATIO,
        duration_seconds=DURATION_SECONDS,
        extra_params={"resolution": RESOLUTION},
    )
    t1 = time.monotonic()
    try:
        submitted = video_provider.submit_video_job(video_request)
    except VideoProviderError as e:
        fail(f"Video submission failed: {e}")
    print(f"      Submitted. Provider job id: {submitted.provider_job_id}")
    print(f"      Estimated video cost: ${submitted.estimated_cost_usd:.4f}")

    JOB_STATE_PATH.write_text(
        json.dumps({"provider_job_id": submitted.provider_job_id, "meta": submitted.meta}, indent=2)
    )
    print(f"      Job state saved to: {JOB_STATE_PATH} (used automatically by recover_fal_video_job.py)")

    print("      Polling for completion (no retries on error - any failure stops here)...")
    result = None
    while True:
        elapsed = time.monotonic() - t1
        if elapsed > MAX_WAIT_SECONDS:
            fail(
                f"Gave up after {elapsed:.0f}s waiting for the video (job {submitted.provider_job_id} "
                "may still complete and be billed on fal.ai's side even though we stopped watching it - "
                "check https://fal.ai/dashboard/billing). We did not retry or resubmit.\n"
                f"      To check on it later without spending anything again, run:\n"
                f"      python -m scripts.recover_fal_video_job {submitted.provider_job_id}"
            )
        try:
            result = video_provider.get_job_status(submitted.provider_job_id, meta=submitted.meta)
        except VideoProviderError as e:
            fail(
                f"Status check failed: {e}\n"
                f"      The job was already submitted (and may be billed) - to check on it later without\n"
                f"      spending anything again, run:\n"
                f"      python -m scripts.recover_fal_video_job {submitted.provider_job_id}"
            )

        if result.status == ProviderJobState.PROCESSING:
            print(f"      ...still processing ({elapsed:.0f}s elapsed)")
            time.sleep(POLL_INTERVAL_SECONDS)
            continue
        break

    video_seconds = time.monotonic() - t1

    if result.status == ProviderJobState.FAILED:
        fail(f"Provider reported generation failure: {result.error_message}")

    print(f"      Completed in {video_seconds:.1f}s")

    try:
        video_provider.download_result(submitted.provider_job_id, result.output_url, str(video_path))
    except VideoProviderError as e:
        fail(
            f"Download failed (generation already succeeded and was billed, but the local save failed): {e}\n"
            f"      To retry just the download without spending anything again, run:\n"
            f"      python -m scripts.recover_fal_video_job {submitted.provider_job_id}"
        )

    actual_video_cost = result.actual_cost_usd if result.actual_cost_usd is not None else submitted.estimated_cost_usd
    total_actual = round(image_result.cost_usd + actual_video_cost, 4)

    manifest["video_path"] = str(video_path)
    manifest["video_cost_usd"] = actual_video_cost
    manifest["actual_cost_usd"] = total_actual
    manifest["completed_at"] = _now()
    save_manifest(manifest)

    print("\n" + "=" * 70)
    print(f"DONE - segment {SEGMENT_ID} generated. No other segment was touched.")
    print("=" * 70)
    print(f"Start-frame image: {image_path}")
    print(f"Segment clip:      {video_path}")
    print(f"Image cost: ${image_result.cost_usd:.4f}   Video cost: ${actual_video_cost:.4f}   Total: ${total_actual:.4f}")
    print(f"Manifest: {MANIFEST_PATH}")
    print("\nSTOP HERE. Review segment_1a.mp4 against:")
    print("  - first 1.5-2s clearly reads as untouched/raw, no structure")
    print("  - clearing progresses via obvious hard jumps, not continuous real-time motion")
    print("  - builder never looks toward camera; camera stays observational")
    print("  - ends on a fully cleared, still-unbuilt site (no stakes/materials yet)")
    print("  - ocean/wind/cloud motion reads as alive")
    print("\nDo not build segment 1B until this segment is reviewed and approved.")


if __name__ == "__main__":
    main()
