"""Project #3 shot-class routing (Creative Brain, production lesson 11).

Every shot is tagged with one of doctrine.SHOT_CLASSES; this table says which fal video
models may generate it and how far each is trusted. Status is evidence, not preference:

    proven_environmental / proven_precision - passed a reviewed proof shot of that class
    candidate_unproven                     - allowed only as a proof shot (allow_unproven=True)
    failed                                 - failed a proof of that class; never selected

A model moves up only by passing a reviewed proof - edit this table with the evidence when that
happens. Stills are never routed here: checkpoint stills (and phase-completion "time jump"
frames) are made manually in ChatGPT and approved in the stills folder.
"""
from dataclasses import dataclass

from app.forma.doctrine import SHOT_CLASSES
from app.providers.video.fal import (
    FAL_VIDEO_MODELS,
    KLING_3_PRO,
    KLING_3_STANDARD,
    SEEDANCE_2_0,
    SEEDANCE_2_5,
    VEO_3_1_FAST_FIRST_LAST,
    WAN_3_0_STANDARD,
    FalVideoModelConfig,
)

STILL_SOURCE = "manual_chatgpt"  # never generated by the pipeline
VIDEO_PROVIDER = "fal"  # Higgsfield is retired to R&D history (recovery only)

PROVEN_ENVIRONMENTAL = "proven_environmental"
PROVEN_PRECISION = "proven_precision"
CANDIDATE_UNPROVEN = "candidate_unproven"
FAILED = "failed"
PROVEN = (PROVEN_ENVIRONMENTAL, PROVEN_PRECISION)


class RoutingError(Exception):
    pass


@dataclass(frozen=True)
class Route:
    model: str  # fal submit path, a key of FAL_VIDEO_MODELS
    status: str
    evidence: str

    @property
    def config(self) -> FalVideoModelConfig:
        return FAL_VIDEO_MODELS[self.model]


# In preference order within each class. time_jump has no video route by design.
SHOT_ROUTES: dict[str, tuple[Route, ...]] = {
    "environmental": (
        Route(WAN_3_0_STANDARD.submit_path, PROVEN_ENVIRONMENTAL,
              "Alpine Video 2 was built on it; train-car clip03 held railcar, location and camera stable. "
              "$0.05/s at 480p. Never for labor (see repetitive_labor)."),
        Route(VEO_3_1_FAST_FIRST_LAST.submit_path, CANDIDATE_UNPROVEN,
              "Hero-reveal upgrade at 720p+ ($0.10/s). Untested on this first/last-frame endpoint."),
    ),
    "repetitive_labor": (
        Route(KLING_3_STANDARD.submit_path, CANDIDATE_UNPROVEN,
              "Native multi_prompt shots map onto rule-11 jump cuts; $0.084/s. clip03 proof not yet run."),
        Route(SEEDANCE_2_0.submit_path, CANDIDATE_UNPROVEN, "Fallback; ~$0.82 per 6 s at 480p. Untested."),
        Route(SEEDANCE_2_5.submit_path, CANDIDATE_UNPROVEN,
              "Real labor motion but stayed on one patch in the single-take clip03 (verdict: revise); "
              "not yet tried with a jump-cut prompt."),
        Route(WAN_3_0_STANDARD.submit_path, FAILED,
              "clip03 2026-09-25: motion_mechanism - morphs toward the end frame instead of doing the labor."),
    ),
    "precision": (
        Route(SEEDANCE_2_5.submit_path, PROVEN_PRECISION,
              "clip03 2026-09-28 (run via Higgsfield, same model and token price as fal): passed the physical "
              "motion test. The fal endpoint itself has not run a job yet. $1.248 per 6 s at 480p."),
        Route(KLING_3_PRO.submit_path, CANDIDATE_UNPROVEN, "$0.112/s. Untested."),
        Route(WAN_3_0_STANDARD.submit_path, FAILED, "clip03 motion_mechanism failure."),
    ),
    "time_jump": (),
}


def routes(shot_class: str) -> tuple[Route, ...]:
    if shot_class not in SHOT_CLASSES:
        raise RoutingError(f"Unknown shot class {shot_class!r} - one of {sorted(SHOT_CLASSES)}.")
    return SHOT_ROUTES[shot_class]


def select_video_model(shot_class: str, *, allow_unproven: bool = False, model: str | None = None) -> Route:
    """The model a shot of this class is generated with.

    Production (allow_unproven=False) gets the first proven route, or a RoutingError naming the
    candidates that need a proof. A proof shot passes allow_unproven=True (and usually `model`)
    to pick a candidate explicitly. Failed routes are never returned.
    """
    if shot_class == "time_jump":
        raise RoutingError("time_jump shots are phase-completion image edits made manually in ChatGPT - "
                           "no video model.")
    options = [r for r in routes(shot_class) if r.status != FAILED and (model is None or r.model == model)]
    if model is not None and not options:
        raise RoutingError(f"{model} is not an allowed route for {shot_class} shots.")
    proven = [r for r in options if r.status in PROVEN]
    if proven:
        return proven[0]
    if allow_unproven and options:
        return options[0]
    candidates = ", ".join(r.model for r in options) or "none"
    raise RoutingError(f"No proven model for {shot_class} shots yet (candidates needing a proof: {candidates}).")
